### ISSUE TITLE
Details title should be center-aligned

### ISSUE THREAD

**Issue by kingfisher13** [axismaps/bcworkshop-services#31]
@bcsheesley Do you concur? See the Country Forest / Jackson Meadows neighborhood for an example.

**Comment by bcsheesley** [comment]
I'd probably say yes if it were a modal screen on a mobile device with the title at the very top, but here I like having the text in the sidebar left-aligned with the logo above and text below. I think it makes for slightly faster reading down that left edge. I do see the issue with long neighborhood names that you point out. Instead of centering, what about truncating and ellipsing (is that a verb?) them at 250px wide?
